@startuml usecaseDiagram

left to right direction

actor "Super Admin" as sAdmin
actor "Admin" as admin
actor "Employee" as user

actor "Developer" as developer

rectangle "TRAKIFY" {
    ' Authentication
    usecase "Login" as login
    usecase "Logout" as logout
    usecase "Register" as register

    ' Account Configuration
    usecase "Manage Organization Details" as manageOrganization
    usecase "Add Courior Credientials" as addCouriorCredentials
    usecase "Edit Courior Credientials" as editCouriorCredentials
    usecase "Delete Courior Credientials" as deleteCouriorCredentials
    usecase "View Courior Credientials" as viewCouriorCredentials

    ' Order Tracking
    usecase "Add Order" as addOrder
    usecase "Edit Order" as editOrder
    usecase "Delete Order" as deleteOrder
    usecase "Add Remarks" as addRemarks
    usecase "Varify Returned Order" as verifyReturnedOrder
    usecase "View Order" as viewOrder

    ' Analytics
    usecase "View Analytics" as viewAnalytics

    ' Employee Management
    usecase "Add Employee" as addEmployee
    usecase "Delete Employee" as deleteEmployee
    usecase "Edit Employee" as editEmployee
    usecase "View Employees" as viewEmployee

    ' Subscription Management
    usecase "Subscribe" as paySubscription
    usecase "Cancel Subscription" as cancelSubscription
    usecase "View Subscription" as viewSubscription

    ' Super Admin Management
    usecase "View Admins" as viewAdmins


}

' Authentication
sAdmin --> login
sAdmin --> logout

admin -u-> login
admin -u-> logout
admin -u-> register

user --> login
user --> logout

developer -u-> login
developer -u-> logout

' Account Configuration
admin -->manageOrganization
admin -->addCouriorCredentials
admin -->editCouriorCredentials
admin -->deleteCouriorCredentials
admin -->viewCouriorCredentials

' Order Tracking
admin -u->addOrder
admin -u->editOrder
admin -u->deleteOrder
admin -u->addRemarks
admin -u->verifyReturnedOrder
admin -u->viewOrder

user -->addOrder
user -->editOrder
user -->deleteOrder
user -->addRemarks
user -->verifyReturnedOrder
user -->viewOrder

' Analytics
admin -u-> viewAnalytics

' Employee Management
admin -u-> addEmployee
admin -u-> deleteEmployee
admin -u-> editEmployee
admin -u-> viewEmployee

' Subscription Management
admin -u-> paySubscription
admin -u-> cancelSubscription
admin -u-> viewSubscription

' Super Admin Management
sAdmin --> viewAdmins


@enduml